Wp\Domain\Model\Commentmeta:
    type: entity
    table: wp_commentmeta
    indexes:
        comment_id:
            columns:
                - comment_id
        meta_key:
            columns:
                - meta_key
    id:
        metaId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: meta_id
            generator:
                strategy: IDENTITY
    fields:
        commentId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: comment_id
        metaKey:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: meta_key
        metaValue:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: meta_value
    lifecycleCallbacks: {  }
