Wp\Domain\Model\TermRelationships:
    type: entity
    table: wp_term_relationships
    indexes:
        term_taxonomy_id:
            columns:
                - term_taxonomy_id
    id:
        objectId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: object_id
        termTaxonomyId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                default: '0'
            id: true
            column: term_taxonomy_id
    fields:
        termOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: term_order
    lifecycleCallbacks: {  }
